name: persona_travel
description: "AI Travel Persona Map"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  drift: ^2.29.0
  envied: ^1.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  google_maps_flutter: ^2.7.0
  webview_flutter: ^4.13.0
  webview_windows: ^0.4.0
  go_router: ^16.3.0
  google_generative_ai: ^0.4.7
  hooks_riverpod: ^3.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  riverpod: ^3.0.3
  sqlite3_flutter_libs: ^0.5.40
  google_maps_flutter_platform_interface: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  drift_dev: ^2.29.0
  envied_generator: ^1.3.1


flutter:
  uses-material-design: true
